
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubeop
  labels:
    chart: kubeop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubeop
    spec:
      containers:
      - name: kubeop
        image: us.gcr.io/studious-lore-148916/kubeop:latest

